# Generated by Django 5.2.11 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_passwordsecurityevent_passwordresetcode_verified_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passwordresetcode",
            old_name="code_hash",
            new_name="code",
        ),
        migrations.RemoveField(
            model_name="passwordresetcode",
            name="email",
        ),
        migrations.RemoveField(
            model_name="passwordresetcode",
            name="verified_at",
        ),
        migrations.AddField(
            model_name="passwordresetcode",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="PasswordSecurityEvent",
        ),
    ]
