"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()

        if value and ((value[0] == value[-1]) and value[0] in {"'", '"'}):
            value = value[1:-1]

        os.environ.setdefault(key, value)


load_env_file(BASE_DIR / ".env")


def get_env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-+#--n_wo)p877zq-a2cxn6cdrr%(!-^v!%bhz=-1ke39m=1$+y")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [host.strip() for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",") if host.strip()]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'prediction',   
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.environ.get("DJANGO_DB_ENGINE", "mssql")

if DB_ENGINE == "mssql":
    from mssql.base import DatabaseWrapper

    DatabaseWrapper._sql_server_versions.setdefault(17, 2022)
    DATABASES = {
        "default": {
            "ENGINE": "mssql",
            "NAME": os.environ.get("DJANGO_DB_NAME", "App"),
            "USER": os.environ.get("DJANGO_DB_USER", "sa"),
            "PASSWORD": os.environ.get("DJANGO_DB_PASSWORD", "123456789"),
            "HOST": os.environ.get("DJANGO_DB_HOST", "localhost"),
            "PORT": os.environ.get("DJANGO_DB_PORT", "1433"),
            "OPTIONS": {
                "driver": os.environ.get("DJANGO_DB_DRIVER", "ODBC Driver 18 for SQL Server"),
                "extra_params": os.environ.get(
                    "DJANGO_DB_EXTRA_PARAMS",
                    "Encrypt=no;TrustServerCertificate=yes;",
                ),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": os.environ.get("DJANGO_DB_NAME", BASE_DIR / "db.sqlite3"),
        }
    }

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "pgh-security-cache",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Tunis'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/filiales/'
LOGOUT_REDIRECT_URL = '/login/'

LOGIN_URL = '/login/'
AUTHENTICATION_BACKENDS = [
    'core.auth_backends.EmailBackend',
]
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "http://127.0.0.1:8000").rstrip("/")
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    os.environ.get("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"),
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", os.environ.get("DJANGO_EMAIL_HOST", ""))
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", os.environ.get("DJANGO_EMAIL_PORT", "587")))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", os.environ.get("DJANGO_EMAIL_HOST_USER", ""))
EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", ""),
)
EMAIL_USE_TLS = get_env_bool(
    "EMAIL_USE_TLS",
    get_env_bool("DJANGO_EMAIL_USE_TLS", True),
)
EMAIL_USE_SSL = get_env_bool(
    "EMAIL_USE_SSL",
    get_env_bool("DJANGO_EMAIL_USE_SSL", False),
)
EMAIL_TIMEOUT = int(os.environ.get("DJANGO_EMAIL_TIMEOUT", "20"))
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "Portail PGH <noreply@app.local>"),
)

# Power BI Configuration
POWERBI_DASHBOARD_EMBED_URL = os.environ.get("POWERBI_DASHBOARD_EMBED_URL", "").strip()
POWERBI_DASHBOARD_OPEN_URL = os.environ.get("POWERBI_DASHBOARD_OPEN_URL", "").strip()

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
