from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views.generic import RedirectView

from core.views import (
    account_password_change_view,
    account_profile_view,
    account_settings_view,
    activate_account_view,
    admin_dashboard,
    article_analysis_view,
    dashboard_view,
    filiale_select,
    filiales_create,
    filiales_delete,
    filiales_list,
    filiales_update,
    forecast_view,
    home,
    login_view,
    ml_predict_view,
    password_reset_request_view,
    password_reset_verify_view,
    purchases_view,
    resend_activation_view,
    sales_view,
    signup,
    signup_pending_view,
    users_create,
    users_delete,
    users_detail,
    users_list,
    users_update,
    workspace_home,
)

urlpatterns = [
    path("admin/portal/", admin_dashboard, name="admin_dashboard"),
    path("admin/users/", users_list, name="users_list"),
    path("admin/users/create/", users_create, name="users_create"),
    path("admin/users/<int:user_id>/", users_detail, name="users_detail"),
    path("admin/users/<int:user_id>/edit/", users_update, name="users_update"),
    path("admin/users/<int:user_id>/delete/", users_delete, name="users_delete"),
    path("admin/filiales/", filiales_list, name="filiales_list"),
    path("admin/filiales/create/", filiales_create, name="filiales_create"),
    path("admin/filiales/<int:filiale_id>/edit/", filiales_update, name="filiales_update"),
    path("admin/filiales/<int:filiale_id>/delete/", filiales_delete, name="filiales_delete"),
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("login/", login_view, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password-reset/", password_reset_request_view, name="password_reset"),
    path("password-reset/verify/", password_reset_verify_view, name="password_reset_verify"),
    path("account/profile/", account_profile_view, name="account_profile"),
    path("account/settings/", account_settings_view, name="account_settings"),
    path("account/password-change/", account_password_change_view, name="account_password_change"),
    path("signup/", signup, name="signup"),
    path("signup/pending/", signup_pending_view, name="signup_pending"),
    path("signup/resend-activation/", resend_activation_view, name="resend_activation"),
    path("activate-account/<uidb64>/<token>/", activate_account_view, name="activate_account"),
    path("filiales/", filiale_select, name="filiale_select"),
    path("espace/", workspace_home, name="workspace_home"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("dashboard/achats/", purchases_view, name="purchases"),
    path("dashboard/ventes/", sales_view, name="sales"),
    path("dashboard/analyse-article/", article_analysis_view, name="article_analysis"),
    path("forecast/", forecast_view, name="forecast"),
    path("ml-predict/", ml_predict_view, name="ml_predict"),
    path("users/", RedirectView.as_view(pattern_name="users_list", permanent=False)),
    path("users/create/", RedirectView.as_view(pattern_name="users_create", permanent=False)),
    path("users/<int:user_id>/", RedirectView.as_view(pattern_name="users_detail", permanent=False)),
    path("users/<int:user_id>/edit/", RedirectView.as_view(pattern_name="users_update", permanent=False)),
    path("users/<int:user_id>/delete/", RedirectView.as_view(pattern_name="users_delete", permanent=False)),
    path("filiales/admin/", RedirectView.as_view(pattern_name="filiales_list", permanent=False)),
    path("prediction/", include("prediction.urls")),
]
